### ISSUE TITLE
Import or dependencies issues

### ISSUE THREAD

**Issue by noraj** [CasperGN/ActiveDirectoryEnumeration#25]
**Describe the bug**

Import or dependencies issues claiming some modules are missing.

**To Reproduce**

To reproduce in a clean fresh environment:

```
$ cd /tmp
$ git clone https://github.com/CasperGN/ActiveDirectoryEnumeration.git && cd ActiveDirectoryEnumeration
$ python -m venv venv
$ source venv/bin/activate
```

Install dependencies `pip3 install .` then there is still problem with dependencies.

```
$ python3 -m activeDirectoryEnum -u x@x -o outputfile --no-creds x.x.x.x
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ActiveDirectoryEnumeration/activeDirectoryEnum.py", line 12, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

$ ./activeDirectoryEnum.py -u x@x -o outputfile --no-creds x.x.x.x
Traceback (most recent call last):
  File "./activeDirectoryEnum.py", line 3, in <module>
    from progressbar import Bar, Percentage, ProgressBar, ETA
ModuleNotFoundError: No module named 'progressbar'
```

I see all dependencies from requirements.txt installed:

```
$ pip3 freeze
ActiveDirectoryEnum==0.3.0
certifi==2020.4.5.1
cffi==1.14.0
chardet==3.0.4
Click==7.0
crypto==1.4.1
cryptography==2.8
dnspython==1.16.0
Flask==1.1.1
future==0.18.2
idna==2.9
impacket==0.9.21
itsdangerous==1.1.0
Jinja2==2.11.1
ldap3==2.7
ldapdomaindump==0.9.2
MarkupSafe==1.1.1
Naked==0.1.31
progressbar==2.5
pyasn1==0.4.8
pycparser==2.20
pycryptodomex==3.9.7
pyOpenSSL==19.1.0
PyYAML==5.3.1
requests==2.23.0
shellescape==3.8.1
six==1.14.0
termcolor==1.1.0
urllib3==1.25.9
Werkzeug==1.0.0
```

Let's try import manually:

```
$ python      
Python 3.8.3 (default, May 17 2020, 18:15:42) 
[GCC 10.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Crypto
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'Crypto'
>>> import progressbar
```

I don't understand why it's not working for `progressbar` but for Crypto it's maybe due to conflict with `cryptography`, `Crypto` and `pycryptodomex`.

![image](https://user-images.githubusercontent.com/16578570/82582415-5150c600-9b92-11ea-9cbf-bac91647697d.png)

I'm not an expert with python but it seems that `pycryptodomex` is self contained and the module name is `Cryptodome`, it's another package `pycryptodome` that use `Crypto`.

See [What is pycryptodomex and how does it differ from pycryptodome?](https://stackoverflow.com/questions/48155294/what-is-pycryptodomex-and-how-does-it-differ-from-pycryptodome)

**Expected behavior**

No module issue.

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Browser N.A.
 - Version N.A.

**Comment by CasperGN** [comment]
Hi!

Thanks a lot for this detailed report. 

I've just pushed https://github.com/CasperGN/ActiveDirectoryEnumeration/tree/issue_25 where I changed from `Crypto.Cipher` to `Cryptodome.Cipher` as the dependencies are indeed not proper - the dome package contains the same as the previous. 
If you'd like to test it out on your side? (I already did mine).
I'll continue to work on the requirements file before it's ready for a PR :-)

/ Casper

**Comment by CasperGN** [comment]
The branch `issue_25` latest seem to do the trick:
```
(master) $ git clone https://github.com/CasperGN/ActiveDirectoryEnumeration.git && cd ActiveDirectoryEnumeration
Cloning into 'ActiveDirectoryEnumeration'...
...
(master) $ python3 -m venv venv
(master) $ source venv/bin/activate
(venv) (master) $ git checkout issue_25
...
(venv) (issue_25) $ pip3 install .
Processing /root/virt_test/ActiveDirectoryEnumeration
...
Successfully installed ActiveDirectoryEnum-0.3.0 Click-7.0 Flask-1.1.1 Jinja2-2.11.1 MarkupSafe-1.1.1 Werkzeug-1.0.0 cffi-1.14.0 cryptography-2.8 dnspython-1.16.0 future-0.18.2 impacket-0.9.21 itsdangerous-1.1.0 ldap3-2.7 ldapdomaindump-0.9.2 progressbar-2.5 pyOpenSSL-19.1.0 pyasn1-0.4.8 pycparser-2.20 pycryptodomex-3.9.7 six-1.14.0 termcolor-1.1.0
(venv) (issue_25) $ python3 -m activeDirectoryEnum
usage: activeDirectoryEnum [-h] [-o OUT_FILE] [-u USER] [-s] [-smb] [-kp] [-bh] [-spn] [--all] [--no-creds] dc

        ___        __  _            ____  _                __                   ______                    
       /   | _____/ /_(_)   _____  / __ \(_)_______  _____/ /_____  _______  __/ ____/___  __  ______ ___ 
      / /| |/ ___/ __/ / | / / _ \/ / / / / ___/ _ \/ ___/ __/ __ \/ ___/ / / / __/ / __ \/ / / / __ `__ \
     / ___ / /__/ /_/ /| |/ /  __/ /_/ / / /  /  __/ /__/ /_/ /_/ / /  / /_/ / /___/ / / / /_/ / / / / / /
    /_/  |_\___/\__/_/ |___/\___/_____/_/_/   \___/\___/\__/\____/_/   \__, /_____/_/ /_/\__,_/_/ /_/ /_/ 
                                                                      /____/                             

|*----------------------------------------------------------------------------------------------------------*|

positional arguments:
  dc                    Hostname of the Domain Controller

optional arguments:
  -h, --help            show this help message and exit
  -o OUT_FILE, --out-file OUT_FILE
                        Path to output file. If no path, CWD is assumed (default: None)
  -u USER, --user USER  Username of the domain user to query with. The username has to be domain name as `user@domain.org`
  -s, --secure          Try to estalish connection through LDAPS
  -smb, --smb           Force enumeration of SMB shares on all computer objects fetched
  -kp, --kerberos_preauth
                        Attempt to gather users that does not require Kerberos preauthentication
  -bh, --bloodhound     Output data in the format expected by BloodHound
  -spn                  Attempt to get all SPNs and perform Kerberoasting
  --all                 Run all checks
  --no-creds            Start without credentials
```

**Comment by noraj** [comment]
I confirm `python3 -m activeDirectoryEnum` works without dep error on branch issue_25

**Comment by CasperGN** [comment]
Superb - thanks a lot for both the bug report and verification. I'll merge the PR #27 now :-)
